# https://github.com/rubocop-hq/rubocop/blob/master/config/default.yml

plugins:
  - rubocop-minitest
  - rubocop-packaging
  - rubocop-performance
  - rubocop-rails

AllCops:
  NewCops: enable
  TargetRubyVersion: 3.1
  Exclude:
    - test/dummy/config/environments/*
    - test/dummy/db/schema.rb
    - test/dummy/tmp/**/*


# Layout
Layout/HashAlignment:
  EnforcedHashRocketStyle: table
  EnforcedColonStyle: table

Layout/LineLength:
  Max: 200


# Packaging
Packaging/BundlerSetupInTests:
  Exclude:
    - test/dummy/config/boot.rb


# Style
Style/ClassAndModuleChildren:
  Exclude:
    - Guardfile

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Exclude:
    - db/migrate/*
    - test/dummy/db/migrate/*

Style/StringConcatenation:
  Exclude:
    - test/test_helper.rb

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/SymbolArray:
  Exclude:
    - test/dummy/config/initializers/filter_parameter_logging.rb
